# Generated by Django 2.2.15 on 2020-09-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200926_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
