# Generated by Django 2.2.15 on 2020-09-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('garage', models.IntegerField(default=0)),
                ('area', models.FloatField()),
                ('photo_main', models.ImageField(upload_to='listings')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='listings')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='listings')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='listings')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='listings')),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='listings/video')),
                ('vr_image', models.ImageField(upload_to='listings/vr')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('type', models.SmallIntegerField(choices=[(0, 'House'), (1, 'Land')], default=0)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('availability', models.SmallIntegerField(choices=[(0, 'Sold'), (1, 'Available'), (2, 'Leased')], default=1)),
                ('views', models.BigIntegerField()),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
