# Generated by Django 2.2.15 on 2020-09-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vr_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/vr'),
        ),
    ]
