# Generated by Django 2.2.15 on 2020-09-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200910_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='author',
        ),
    ]
