# Generated by Django 2.2.15 on 2020-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default=1, upload_to='listings/img', verbose_name='Main Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='listings/img'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='listings/img'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='listings/img'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='listings/img'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=40),
        ),
    ]
