# Generated by Django 2.2.15 on 2020-09-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200914_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='status',
        ),
    ]
