# Generated by Django 2.2.15 on 2020-09-19 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_remove_wishlist_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transactions', verbose_name='Teller Image')),
                ('teller_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bank', models.PositiveSmallIntegerField(choices=[(0, 'Zenith Bank'), (1, 'Fidelity Bank'), (2, 'Access Bank')], default=0)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(0, 'Bank Transfer'), (1, 'Bank Deposit')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Submitted'), (1, 'Pending'), (2, 'Allocated')])),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
        ),
    ]
