# Generated by Django 2.2.15 on 2020-09-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='image',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='transactions', verbose_name='Teller Image/File'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Submitted'), (1, 'Paid'), (2, 'Allocated')], default=0),
        ),
    ]
