# Generated by Django 2.2.15 on 2020-09-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200919_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Bank Transfer'), (1, 'Bank Deposit')], null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Submitted'), (1, 'Paid'), (2, 'Allocated')], null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
